# habilidades_cartas.py

habilidades_cartas = {
    "Carta_1": "Investida: +1 ATK neste turno",
    "Carta_2": "Regenerar: Recupera 2 de vida",
    "Carta_3": "Voo: Ignora bloqueadores terrestres",
    "Carta_4": "Explosão: Causa 2 de dano em área",
    "Carta_5": "Resistência: +1 DEF por 1 turno",
    "Carta_6": "Tiro Rápido: Ataca duas vezes",
    "Carta_7": "Enraizar: Ganha +2 DEF",
    "Carta_8": "Curar: Recupera 2 de vida de um aliado",
    "Carta_9": "Fúria: +2 ATK quando com pouca vida",
    "Carta_10": "Camuflagem: Não pode ser alvo no próximo turno",
    "Carta_11": "Intangível: Imune a ataques físicos por 1 turno",
    "Carta_12": "Ressuscitar: Revive uma criatura",
    "Carta_13": "Exército Zumbi: Ressuscita uma carta destruída da pilha de descarte",
    "Carta_14": "Apodrecer: Causa -1 DEF ao inimigo",
    "Carta_15": "Drenar Vida: Cura igual ao dano recebido",
    "Carta_16": "Coragem: +1 ATK para aliados",
    "Carta_17": "Voo: ATK 2 pontos de vida por cima ignorando as defesas",
    "Carta_18": "Luz Curativa: Recupera 3 de vida para todos aliados",
    "Carta_19": "Moral Alta: +1 ATK se houver outro aliado",
    "Carta_20": "Precisão: ATAK 2 de vida direto no Herói",
    "Carta_21": "Impede o inimigo de atacar no próximo turno.",
    "Carta_22": "Concede 2 de defesa extra a um aliado ao ser invocada.",
    "Carta_23": "Cura 3 pontos de vida ao jogador ao ser jogado.",
    "Carta_24": "Aumenta o ataque de todas as cartas aliadas da floresta em +1.",
    "Carta_25": "Força o inimigo a descartar uma carta da mão.",
    "Carta_26": "Lamento Eterno: Impede um inimigo de usar habilidade no próximo turno",
    "Carta_27": "Reflexo Veloz: Ganha +1 ATK ao bloquear um ataque",
    "Carta_28": "Marejada Silenciosa: Impede o inimigo de atacar no próximo turno",
    "Carta_29": "Labareda Final: Causa 2 de dano ao inimigo ao ser destruído",
    "Carta_30": "Erupção: Causa 1 de dano em todos os inimigos",
    "Carta_31": "Casca de Magma: Reduz em 1 todo dano recebido",
    "Carta_32": "Estabilidade Arcana: Imune a todos ataques por 1 turno",
    "Carta_33": "Luz do Crepúsculo: Restaura 2 de vida ao Herói",
    "Carta_34": "Olhar Assombrado: -2 DEF em uma carta inimiga",
    "Carta_35": "Explosão Volátil: Causa dano igual ao seu ATK ao ser destruído",
    "Carta_36": "Semente Venenosa: Causa 3 de dano por 2 turnos ao inimigo",
    "Carta_37": "Bruma Calmante: Cura 2 de vida ao jogador por turno",
    "Carta_38": "Sombras Persistentes: Retorna à mão do jogador ao morrer (1 vez)",
    "Carta_39": "Incinerar: Causa 3 de dano diretamente o jogador",
    "Carta_40": "Vínculo com a Natureza: Ganha +1 ATK por cada carta Floresta em campo",
    "Carta_41": "Dissolução Espiritual: Impede o inimigo de usar habilidade por 1 turno",
    "Carta_42": "Golpe Divino: Causa dano igual à sua DEF em um inimigo",
    "Carta_43": "Manto Aquático: Concede +2 DEF a um aliado",
    "Carta_44": "Ira Selvagem: Aumenta o ATK de todos aliados Floresta em +1",
    "Carta_45": "Chama Serena: Cura 1 ponto de vida por turno",
    "Carta_46": "Proteção Sagrada: Bloqueia o primeiro dano recebido",
    "Carta_47": "Alívio Profundo: Cura 3 pontos de vida do heroi",
    "Carta_48": "Chamas Eternas: Causa 1 de dano contínuo por 2 turnos ao inimigo",
    "Carta_49": "Toque Revitalizante: Cura 1 ponto de vida por criatura aliada",
    "Carta_50": "Reflexo Solar: Reflete 2 de dano ao atacante",
    "Carta_51": "Marcas das Trevas: Inimigo recebe +1 de dano de todas as fontes",
    "Carta_52": "Força da Selva: Aumenta o ATK de todas as cartas Floresta em +1",
    "Carta_53": "Ciclone Arcano: Move uma carta inimiga de volta para mão do inimigo",
    "Carta_54": "Aparição Cruel: Ataca novamente se destruir um inimigo",
    "Carta_55": "Olhar Sombrio: Diminui o ATK de uma carta inimiga em 2",
    "Carta_56": "Retorno Obscuro: Retorna ao topo do deck ao ser destruído",
    "Carta_57": "Escudo Celestial: Reduz em 2 o dano recebido por aliados neste turno",
    "Carta_58": "Chamas Vorazes: Causa 2 de dano a todos inimigos com DEF ≤ 3",
    "Carta_59": "Barreira de Cinzas: Impede ataques de criaturas com ATK ≥ 5 no turno",
    "Carta_60": "Fagulha Final: Causa 3 de dano ao ser destruído",
    "Carta_61": "Rugido Flamejante: Enfraquece (−1 ATK) todos inimigos no turno",
    "Carta_62": "Tsunami: Causa 2 de dano e recua todas as cartas inimigas 1 slot",
    "Carta_63": "Canto Místico: Cura 2 de vida para o jogador a cada turno",
    "Carta_64": "Maré Protetora: Concede +1 DEF a todos aliados por 2 turnos",
    "Carta_65": "Emboscada Aquática: Ataca primeiro ao ser invocado",
    "Carta_66": "Aprisionar: Impede uma carta inimiga de atacar no próximo turno",
    "Carta_67": "Espinhos Reativos: Causa 3 de dano quando recebe ataque (1 turno)",
    "Carta_68": "Chamado da Floresta: Invoca 1 carta da floresta da pilha de descarte",
    "Carta_69": "Voo Rasante: Ataca direto o herói ignorando cartas com DEF > 4",
    "Carta_70": "Dispersão Mágica: Devolve uma carta inimiga à mão do oponente",
    "Carta_71": "Raio Estático: Causa 1 de dano em até duas cartas inimigas",
    "Carta_72": "Terror Primordial: O oponente descarta uma carta aleatória",
    "Carta_73": "Reforço de Rocha: +2 DEF permanente ao ser invocado",
    "Carta_74": "Proteção Natural: Bloqueia o primeiro ataque recebido",
    "Carta_75": "Justiça Ardente: +2 ATK a todos os aliados de Luz",
    "Carta_76": "Bênção Matinal: Cura 2 de vida em todas aliados",
    "Carta_77": "Aura de Serenidade: Nenhuma carta pode atacar no próximo turno",
    "Carta_78": "Despertar: Uma carta aliada destruída volta com 1 de vida",
    "Carta_79": "Presença Amaldiçoada: -1 ATK para todos inimigos enquanto estiver em campo",
    "Carta_80": "Colheita Sombria: Cura o jogador em 1 para cada inimigo destruído",
}

def get_habilidade_por_id(carta_id: str) -> str:
    return habilidades_cartas.get(carta_id, "Nenhuma habilidade registrada.")
